// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error)
	DeleteTransaction(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	DeleteWallet(ctx context.Context, id int64) error
	GetTransaction(ctx context.Context, id int64) (Transaction, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetWallet(ctx context.Context, id int64) (Wallet, error)
	ListTransaction(ctx context.Context, arg ListTransactionParams) ([]Transaction, error)
	ListUser(ctx context.Context, arg ListUserParams) ([]User, error)
	ListWallet(ctx context.Context, arg ListWalletParams) ([]Wallet, error)
	UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
	UpdateWallet(ctx context.Context, arg UpdateWalletParams) error
	lockWalletsForUpdate(ctx context.Context, ids []int64) ([]Wallet, error)
}

var _ Querier = (*Queries)(nil)
